language: python
branches:
  only:
    - master

python:
  - "3.7"

install:
  - pip install -r requirements.yml

script:
  - pytest 
  - coverage run --source=./tracklib -m py.test
  - cd doc
  - make html

after_success:
  - coveralls

  
