language: python

python:
  - "3.7"

install:
  - pip install -r requirements.yml

script:
  - pytest --cov=tracklib test/
  - coverage run --source=./tracklib -m py.test
  - cd doc
  - make html

after_success:
  - coveralls

  
