dist: xenial
language: python
branches:
  only:
    - main

python:
  - "3.7"

install:
  - pip install -r requirements.yml

script:
  - pytest test/
  - pytest --cov-config=.coveragerc --cov=tracklib test/
  - cd doc
  - make html

after_success:
  - codecov

  
